### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by h7kanna** [boa-dev/boa#3983] opened 2024-09-05 21:34 UTC
**Describe the bug**
This is exactly not a bug of boa, but compilation failure due to backward incompatible change to dependency 'intrusive-collections'

**Expected behavior**
Update the code to be compatible with latest  or pin it until the actual fix by
intrusive-collections = { version = "=0.9.6"}

**Build environment (please complete the following information):**

- OS: MacOS
- Version: v0.19
- Target triple: [aarch64-apple-darwin](https://doc.rust-lang.org/nightly/rustc/platform-support/apple-darwin.html)
- Rustc version: rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**Additional context**

Causing commit
https://github.com/Amanieu/intrusive-rs/issues/92

https://github.com/Amanieu/intrusive-rs/pull/93

```
error[E0277]: `Cell<std::option::Option<NonNull<LinkedListLink>>>` cannot be shared between threads safely
   --> /Users/h7kanna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boa_engine-0.19.0/src/builtins/atomics/futex.rs:161:37
    |
161 | pub(crate) static CRITICAL_SECTION: Mutex<FutexWaiters> = Mutex::new(FutexWaiters {
    |                                     ^^^^^^^^^^^^^^^^^^^ `Cell<std::option::Option<NonNull<LinkedListLink>>>` cannot be shared between threads safely
    |
    = help: within `FutexWaiter`, the trait `Sync` is not implemented for `Cell<std::option::Option<NonNull<LinkedListLink>>>`, which is required by `Mutex<FutexWaiters>: Sync`
    = note: if you want to do aliasing and mutation between multiple threads, use `std::sync::RwLock`
note: required because it appears within the type `LinkedListLink`
   --> /Users/h7kanna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/intrusive-collections-0.9.7/src/linked_list.rs:63:12
    |
63  | pub struct Link {
    |            ^^^^
note: required because it appears within the type `FutexWaiter`
   --> /Users/h7kanna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boa_engine-0.19.0/src/builtins/atomics/futex.rs:167:19
    |
167 | pub(crate) struct FutexWaiter {
    |                   ^^^^^^^^^^^
    = note: required for `UnsafeRef<FutexWaiter>` to implement `Send`
    = note: 2 redundant requirements hidden
    = note: required for `alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Owned, usize, intrusive_collections::LinkedList<FutexWaiterAdapter>, alloc::collections::btree::node::marker::LeafOrInternal>` to implement `Send`
note: required because it appears within the type `std::option::Option<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Owned, usize, intrusive_collections::LinkedList<FutexWaiterAdapter>, alloc::collections::btree::node::marker::LeafOrInternal>>`
   --> /Users/h7kanna/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:574:10
    |
574 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type `BTreeMap<usize, intrusive_collections::LinkedList<FutexWaiterAdapter>>`
   --> /Users/h7kanna/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/collections/btree/map.rs:173:12
    |
173 | pub struct BTreeMap<
    |            ^^^^^^^^
note: required because it appears within the type `small_map::Inner<usize, intrusive_collections::LinkedList<FutexWaiterAdapter>, 16>`
   --> /Users/h7kanna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boa_engine-0.19.0/src/small_map/mod.rs:30:6
    |
30  | enum Inner<K, V, const ARRAY_SIZE: usize> {
    |      ^^^^^
note: required because it appears within the type `SmallMap<usize, intrusive_collections::LinkedList<FutexWaiterAdapter>, 16>`
   --> /Users/h7kanna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boa_engine-0.19.0/src/small_map/mod.rs:25:19
    |
25  | pub(crate) struct SmallMap<K, V, const ARRAY_SIZE: usize> {
    |                   ^^^^^^^^
note: required because it appears within the type `FutexWaiters`
   --> /Users/h7kanna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boa_engine-0.19.0/src/builtins/atomics/futex.rs:178:19
    |
178 | pub(crate) struct FutexWaiters {
    |                   ^^^^^^^^^^^^
    = note: required for `Mutex<FutexWaiters>` to implement `Sync`
    = note: shared static variables must have a type that implements `Sync`
```

**Comment by jedel1043** [comment] 2024-09-05 21:58
Duplicate of #3982.

**Closed by jedel1043** 2024-09-05 21:58 UTC
