### ISSUE TITLE
Uncaught "ReferenceError" when using undefined variables

### ISSUE THREAD

**Issue by aalykiot** [boa-dev/boa#1764] opened 2021-12-26 16:03 UTC
Trying to use an **undefined** variable to produce an outcome throws an `Uncaught "ReferenceError"` error.

```js
typeof module === "object" ? module.exports : {};
```

The rest of the JS engines can handle undefined behaviour like the above without throwing errors.

Is it a bug in Boa ?? An unimplemented feature ?? Or this is happening by design ??

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

Thanks!

**Comment by HalidOdat** [comment] 2022-10-22 21:34
@aalykiot the above code to reproduce the error. Seems to be fixed and returns the empty object as expected.

So closing this.

**Closed by HalidOdat** 2022-10-22 21:34 UTC
Labels: bug
