### ISSUE TITLE
panic: 'binding index must be in range'

### ISSUE THREAD

**Issue by langston-barrett** [boa-dev/boa#2655] opened 2023-03-13 19:04 UTC
**Describe the bug**
```
thread 'main' panicked at 'binding index must be in range', boa_engine/src/environments/runtime.rs:601:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/option.rs:1924:5
   5: boa_engine::environments::runtime::DeclarativeEnvironmentStack::put_value
   6: <boa_engine::vm::opcode::define::DefInitVar as boa_engine::vm::opcode::Operation>::execute
   7: boa_engine::vm::<impl boa_engine::context::Context>::execute_instruction
   8: boa_engine::vm::<impl boa_engine::context::Context>::run
   9: boa_engine::context::Context::execute
  10: boa_engine::builtins::eval::Eval::perform_eval
  11: <boa_engine::vm::opcode::call::CallEval as boa_engine::vm::opcode::Operation>::execute
  12: boa_engine::vm::<impl boa_engine::context::Context>::execute_instruction
  13: boa_engine::vm::<impl boa_engine::context::Context>::run
  14: boa_engine::vm::code_block::<impl boa_engine::object::jsobject::JsObject>::call_internal
  15: boa_engine::object::internal_methods::function::function_call{{reify.shim}}
  16: <boa_engine::vm::opcode::call::Call as boa_engine::vm::opcode::Operation>::execute
  17: boa_engine::vm::<impl boa_engine::context::Context>::execute_instruction
  18: boa_engine::vm::<impl boa_engine::context::Context>::run
  19: boa_engine::context::Context::execute
  20: boa_engine::context::Context::eval_script
  21: boa::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**To Reproduce**

Minimized from a ChakraCore test case with [`treereduce`](https://github.com/langston-barrett/treereduce)

```javascript
(function Test1() {
    try {
        eval("function f(x,x) {}");
    } catch (e) {
    }
})();
```

**Build environment (please complete the following information):**

- OS: rust docker container
- Target triple: x86_64-unknown-linux-gnu
- Rustc version: 1.68

**Other**

Let me know if you want me to report panics like this, I have several already and can create a whole bunch more.

**Comment by jedel1043** [comment] 2023-03-13 19:23
This is probably a duplicate of #2317, so closing for now.
> Let me know if you want me to report panics like this, I have several already and can create a whole bunch more.
Please do!

**Closed by jedel1043** 2023-03-13 19:23 UTC
Labels: bug
