### ISSUE TITLE
Implement missing RegExp properties

### ISSUE THREAD

**Issue by RageKnify** [boa-dev/boa#1304] opened 2021-06-06 17:36 UTC
**ECMASCript feature**
The description of the RegExp Constructor is here: https://tc39.es/ecma262/#sec-regexp-constructor

**Example code**
MDN should have enough examples to test, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

- [x] `get RegExp [ @@species ]`
- [x] `RegExp.prototype.constructor`
- [x] `RegExp.prototype [ @@match ] ( string )`
- [x] `RegExp.prototype [ @@matchAll ] ( string )`
- [x] `RegExp.prototype [ @@replace ] ( string, replaceValue )`
- [x] `RegExp.prototype [ @@search ] ( string )`
- [x] `get RegExp.prototype.source`
- [x] `RegExp.prototype [ @@split ] ( string, limit )`

Part of the code for `@@replace` is in `String.prototype.replace` and should be removed from there.
https://github.com/boa-dev/boa/blob/2e75dd8cc3c032891b69636ff2961b27fb88d1ca/boa/src/builtins/string/mod.rs#L648

**Comment by raskad** [comment] 2021-06-15 13:05
I am currently working on this.

**Comment by raskad** [comment] 2021-07-19 21:59
Depending on how we want to define this issue, I think we could mark some items on the list as done or close this issue.
The following is the current state of the built-ins/RegExp/prototype test suite:

|Test Suite|Total|Passed|
|---|---|---|
|RegExp.prototype|880|713|
|Symbol.species|8|8|
|Symbol.match|102|100|
|Symbol.matchAll|52|34|
|Symbol.replace|134|105|
|Symbol.search|46|38|
|source|24|12|
|Symbol.split|88|54|

My feeling is that a big part of the failing tests is based on missing features, either somewhere in boa or in regress. For the most part, I think the basic features are implemented.

**Comment by RageKnify** [comment] 2021-07-19 23:57
> Depending on how we want to define this issue, I think we could mark some items on the list as done or close this issue.

My opinion is that if a function is spec compliant we can consider it done.

Tests that depend on regress implementing more things could be open as separate issues and include a link to regress's issue so that we have something tracking it here.

If the failing tests depend on things being implemented elsewhere in boa (for example `Reflect` is used in a lot of tests outside its folder) then we can also consider that function done, and it might be a good idea to open an issue for the missing feature if none exist.

**Comment by raskad** [comment] 2021-07-24 21:37
I've looked trough all of the failing tests for the RegExp/prototype tests. Here is a list of the related feature / bugfix that is necessary for the tests to pass.

| Feature / Bug                               | Failing test      |
|---------------------------------------------|-------------------|
| Named capture groups #1390 (ready for merge) | <ul><li>Symbol.replace/named-groups</li><li>Symbol.replace/result-coerce-groups-prop-err</li><li>Symbol.replace/result-coerce-groups-prop</li><li>Symbol.replace/result-coerce-groups</li><li>Symbol.replace/result-get-groups-prop-err</li></ul> |
| Fixed in my next PR (after #1390 merge) | <ul><li>Symbol.matchAll/regexpcreate-this-throws</li><li>Symbol.search/set-lastindex-init-samevalue</li><li>Symbol.search/set-lastindex-restore-samevalue</li><li>Symbol.search/success-get-index-err</li><li>Symbol.search/set-lastindex-restore-err</li><li>Symbol.replace/subst-capture-idx-1</li><li>Symbol.replace/subst-capture-idx-2</li><li>Symbol.replace/poisoned-stdlib</li><li>Symbol.replace/arg-2-coerce-err</li><li>Symbol.replace/get-unicode-error</li></ul> |
| Support for shorthand object literals #1308 | <ul><li>Symbol.matchAll/species-regexp-get-unicode-throws</li><li>Symbol.matchAll/species-constructor-species-throws</li><li>Symbol.matchAll/isregexp-this-throws</li><li>Symbol.matchAll/isregexp-called-once</li><li>Symbol.matchAll/species-constructor-species-is-null-or-undefined</li><li>Symbol.matchAll/species-constructor-get-species-throws</li><li>Symbol.matchAll/species-regexp-get-global-throws</li><li>Symbol.matchAll/species-constructor</li></ul> |
| `new Object("a").toString()` does not return `'a'`  | <ul><li>exec/S15.10.6.2_A1_T3</li></ul> |
| RegExp hasIndices | <ul><li>flags/return-order</li><li>flags/rethrow</li><li>flags/coercion-hasIndices</li><li>flags/get-order</li><li>flags/this-val-regexp</li></ul> |
| Implementing the eval function #948 | <ul><li>source/value</li><li>source/value-line-terminator</li><li>source/value-slash</li><li>source/value-empty</li><li>source/value-u</li></ul> |
| Realm related? | <ul><li>ignoreCase/cross-realm</li><li>dotAll/cross-realm</li><li>sticky/cross-realm</li><li>multiline/cross-realm</li><li>source/cross-realm</li><li>unicode/cross-realm</li><li>hasIndices/cross-realm</li><li>global/cross-realm</li></ul> |
| `new` Operator without parentheses | <ul><li>exec/S15.10.6.2_A1_T14</li><li>exec/S15.10.6.2_A7</li><li>exec/S15.10.6.2_A2_T1</li><li>toString/S15.10.6.4_A7</li><li>test//S15.10.6.3_A1_T14</li><li>test//S15.10.6.3_A7</li><li>test//S15.10.6.3_A2_T1</li></ul> |
| `'𝌆'[1] == '\udf06'` should be `true` | <ul><li>exec/u-captured-value</li></ul> |
| regress is always assumes the unicode flag | <ul><li>dotall/without-dotall</li></ul> |
| Last expressions result gets returned from functions when there is no return #672 | <ul><li>Symbol.replace/fn-invoke-args-empty-result</li><li>Symbol.replace/fn-invoke-args</li><li>Symbol.replace/fn-invoke-this-no-strict</li></ul> |
| Root cause not identified. Seems to be somehow related to species constructor? | <ul><li>Symbol.split/str-match-err</li><li>Symbol.split/species-ctor-y</li><li>Symbol.split/str-result-coerce-length</li><li>Symbol.split/species-ctor</li><li>Symbol.split/str-set-lastindex-no-match</li><li>Symbol.split/str-result-get-capture-err</li><li>Symbol.split/str-result-get-length-err</li><li>Symbol.split/str-set-lastindex-match</li><li>Symbol.split/str-coerce-lastindex-err</li><li>Symbol.split/str-get-lastindex-err</li><li>Symbol.split/species-ctor-err</li><li>Symbol.split/str-empty-match-err</li><li>Symbol.split/coerce-flags</li><li>Symbol.split/str-set-lastindex-err</li><li>Symbol.split/splitter-proto-from-ctor-realm</li><li>Symbol.split/str-result-coerce-length-err</li><li>Symbol.split/str-coerce-lastindex</li></ul> |
| Root cause not identified | <ul><li>Symbol.match/builtin-infer-unicode</li><li>Symbol.replace/coerce-unicode</li><li>exec/S15.10.6.2_A4_T5</li><li>exec/S15.10.6.2_A1_T20</li></ul> |

**Comment by jedel1043** [comment] 2021-09-08 03:45
Closing because #1434 solved most, if not all, the differences from the spec.

**Closed by jedel1043** 2021-09-08 03:45 UTC
Labels: enhancement, good first issue, builtins
