### ISSUE TITLE
cannot use regex "/=/" in string.replace

### ISSUE THREAD

**Issue by piaoger** [boa-dev/boa#2379] opened 2022-10-24 20:26 UTC
**Describe the bug**

Run a piece of code to replace string with regex in Boa Playground and found an error.

**To Reproduce**
Steps to reproduce the issue, or JavaScript code that causes this failure.
 
This JavaScript code reproduces the issue:
```javascript
"A=B".replace(/=/g,"!=")
```
 
**Expected behavior**
Explain what you expected to happen, and what is happening instead.

It should be:
```text
A!=B
```
But got below error in Boa Playgound
```text
Uncaught "SyntaxError": "unexpected token '/=', primary expression at line 1, col 15"
```

**Build environment (please complete the following information):**

- OS: [Window11]
- Chrome 64bit
- Boa Playground

**Additional context**

**Comment by Razican** [comment] 2022-10-25 17:34
I'm almost certain that this is a duplicate of #2327, and it's fixed for the next version. I'll check it today or tomorrow to confirm it.

**Closed** 2022-10-25 17:55 UTC
Labels: bug, parser
