### ISSUE TITLE
Referencing an declared variable return `undefined`

### ISSUE THREAD

**Issue by HalidOdat** [boa-dev/boa#453] opened 2020-06-03 23:33 UTC
**Describe the bug**

Referencing any declared variable return `undefined`.

**To Reproduce**
Steps to reproduce the issue, or JavaScript code that causes this failure.

```javascript
x
```
*Note*: `x` was not declared previously.

**Actual behavior**
```javascript
undefined
```

**Expected behavior**
It should throw a `ReferenceError`, since we don't have a `RefereceError` it should at least `panic`

**Build environment:**
 - OS: Manjaro Linux
 - Target triple: x86_64-unknown-linux-gnu
 - Rustc version: rustc 1.43.1 (8d69840ab 2020-05-04)

**Comment by KrisChambers** [comment] 2020-06-17 19:30
I can take a look at this.

**Comment by Razican** [comment] 2020-06-17 19:47
Isn't this a duplicate of #463? I think it should have been resolved already.

**Comment by HalidOdat** [comment] 2020-06-17 20:05
> Isn't this a duplicate of #463? I think it should have been resolved already.

Yes. this is a duplicate. I'll close this

**Closed** 2020-06-17 20:05 UTC
Labels: bug, duplicate, execution, good first issue
